openapi: 3.0.0
info:
  version: "1.0.0"
  title: DoH
  description: Versión simplificada de DoH (DNS over HTTPS)

servers:
  - url: http://localhost:8080/api
    description: Servidor de desarrollo

# Paths servidos por la aplicación
paths:
  /custom-domains:
    post:
      operationId: "api.domains.create_custom_domain"
      tags:
        - "CustomDomains"
      summary: "Alta de un custom domain al sistema"
      description: "Crea un nuevo custom domain y lo guarda en memoria"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputCustomDomain'
      responses:
        201:
          description: "Se creo el custom domain correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomDomain'
        400:
          description: "El custom domain ya fue creado con anterioridad, o se quiso crear con algún campo faltante"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /custom-domains/{domain}:
    delete:
      operationId: "api.domains.delete_custom_domain"
      tags:
        - "CustomDomains"
      summary: "Borrar un custom domain del sistema"
      description: "Borra un custom domain del sistema"
      parameters:
        - in: path
          name: domain
          required: true
          description: El domain a borrar
          schema:
            type: string
      responses:
        204:
          description: "El custom domain fue borrado con éxito"
          #content:
          #  application/json:
          #    schema:
          #      $ref: '#/components/schemas/DeletedCustomDomain'
        404:
          description: "El custom domain no fue encontrado en el sistema"
    put:
      operationId: "api.domains.modify_existent_domain"
      tags:
      - "CustomDomains"
      summary: "Modificar la ip de un custom domain"
      description: "Modifica la ip de un custom domain dado por path variable"
      parameters:
      - in: path
        name: domain
        required: true
        description: El domain a modificar
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputCustomDomain'
      responses:
        200:
          description: "El custom domain fue modificado con éxito"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomDomain'
        400:
          description: "El body del request está mal formado"
        404:
          description: "El custom domain no fue encontrado en el sistema"

# Declaración de tipos de datos
components:
  schemas:
    CustomDomain:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
        custom:
          type: "boolean"
    InputCustomDomain:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
    Error:
      type: "object"
      properties:
        error:
          type: "string"
    #DeletedCustomDomain:
    #  type: "object"
    #  properties:
    #    domain:
    #      tyoe: "string"
