openapi: 3.0.0
info:
  version: "1.0.0"
  title: DoH
  description: Versión simplificada de DoH (DNS over HTTPS)

servers:
  - url: http://localhost:8080/api
    description: Servidor de desarrollo

# Paths servidos por la aplicación
paths:
  /domains/{domain}:
    get:
      operationId: "api.domains.get_domain"
      tags:
        - "Domain"
      summary: "Obtiene la IP asociada a un dominio en particular"
      description: "Obtiene la IP asociada a un dominio en particular, pudiendo ser este un custom domain creado previamente."
      parameters:
        - in: path
          name: domain
          required: true
          schema:
            type: string
          description: El nombre de dominio a consultar
      responses:
        200:
          description: "Operación de consulta exitosa"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomDomain'
        404:
          description: "No se encontró el dominio en el Resolver"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /custom-domains:
    get:
      operationId: "api.domains.get_custom_domains"
      tags:
        - "CustomDomains"
      summary: "Colección de los dominios existentes"
      description: "Devuelve el listado de dominios existentes en el sistema"
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: Filtro a aplicarse sobre los nombres de dominio
      responses:
        200:
          description: "Operación de consulta exitosa"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomDomains'
    post:
      operationId: "api.domains.create_custom_domain"
      tags:
        - "CustomDomains"
      summary: "Alta de un custom domain al sistema"
      description: "Crea un nuevo custom domain y lo guarda en memoria"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputCustomDomain'
      responses:
        201:
          description: "Se creo el custom domain correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomDomain'
        400:
          description: "El custom domain ya fue creado con anterioridad, o se quiso crear con algún campo faltante"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /custom-domains/{domain}:
    delete:
      operationId: "api.domains.delete_custom_domain"
      tags:
        - "CustomDomains"
      summary: "Borrar un custom domain del sistema"
      description: "Borra un custom domain del sistema"
      parameters:
        - in: path
          name: domain
          required: true
          description: El domain a borrar
          schema:
            type: string
      responses:
        200:
          description: "El custom domain fue borrado con éxito"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeletedCustomDomain'
        404:
          description: "El custom domain no fue encontrado en el sistema"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      operationId: "api.domains.modify_existent_domain"
      tags:
      - "CustomDomains"
      summary: "Modificar la ip de un custom domain"
      description: "Modifica la ip de un custom domain dado por path variable"
      parameters:
      - in: path
        name: domain
        required: true
        description: El domain a modificar
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputCustomDomain'
      responses:
        200:
          description: "El custom domain fue modificado con éxito"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomDomain'
        400:
          description: "El body del request está mal formado"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: "El custom domain no fue encontrado en el sistema"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

# Declaración de tipos de datos
components:
  schemas:
    CustomDomain:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
        custom:
          type: "boolean"
    CustomDomains:
      type: "object"
      properties:
        items:
          type: "array"
          items:
            $ref: '#/components/schemas/CustomDomain'
    InputCustomDomain:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
    Error:
      type: "object"
      properties:
        error:
          type: "string"
    DeletedCustomDomain:
      type: "object"
      properties:
        domain:
          type: "string"
